### ISSUE TITLE
Publish Lix in hex.pm

### ISSUE THREAD

**Issue by rfunix** [rfunix/lix#3]

**Comment by altyaper** [comment]
I will create a PR for this, *mix.exs* needs a `name` and an `source_url` so this can be registered in hex

**Comment by altyaper** [comment]
Created https://github.com/rfunix/lix/pull/8

**Comment by altyaper** [comment]
I think this can be closed since lix is already in hex.pm https://hex.pm/packages/lix

**Comment by rfunix** [comment]
Thanks @echavezNS
