### ISSUE TITLE
Add newrelic support

### ISSUE THREAD

**Issue by rfunix** [rfunix/lix#5]
https://github.com/newrelic/elixir_agent

**Comment by altyaper** [comment]
What exactly do you need here? just add the dependency and a proper configuration?

**Comment by rfunix** [comment]
Hi @echavezNS , yes and ... 

I think, it's cool, add @trace

```
defmodule MyModule do
  use NewRelic.Tracer

  @trace :func
  def func do
    # Will report as `MyModule.func/0`
  end
end
```

in handler callbacks:
https://github.com/rfunix/lix/blob/master/lib/lix/handler/handler.ex
